// This file is auto-generated by @hey-api/openapi-ts

import { http, type HttpHandler, HttpResponse, type HttpResponseResolver, type RequestHandlerOptions as RequestHandlerOptions2 } from 'msw';

import type { ClientOptions, GetClusterResponses, GetGraphResponses, GetHealthResponses, GetMetaResponses, GetNodeResponses, GetNodeSubgraphResponses, GetTopNodesResponses, ListClustersResponses, ReloadDataResponses, SearchNodesResponses } from './types.gen';

export type RequestHandlerOptions = RequestHandlerOptions2 & {
    baseUrl?: ClientOptions['baseUrl'];
    responseFallback?: 'error' | 'passthrough';
};

export type HandleGetHealthResponse = {
    body: GetHealthResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /health` operation.
 */
export function handleGetHealth(response?: HandleGetHealthResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<never, never>(`${options?.baseUrl ?? '*'}/health`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleGetMetaResponse = {
    body: GetMetaResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /meta` operation.
 */
export function handleGetMeta(response?: HandleGetMetaResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<never, never>(`${options?.baseUrl ?? '*'}/meta`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleReloadDataResponse = {
    body: ReloadDataResponses[200];
    status?: 200;
};

/**
 * Handler for the `POST /reload` operation.
 */
export function handleReloadData(response?: HandleReloadDataResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.post<never, never>(`${options?.baseUrl ?? '*'}/reload`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleGetGraphResponse = {
    body: GetGraphResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /graph` operation.
 */
export function handleGetGraph(response?: HandleGetGraphResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<never, never>(`${options?.baseUrl ?? '*'}/graph`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleSearchNodesResponse = {
    body: SearchNodesResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /search` operation.
 */
export function handleSearchNodes(response?: HandleSearchNodesResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<never, never>(`${options?.baseUrl ?? '*'}/search`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleGetNodeResponse = {
    body: GetNodeResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /nodes/{gid}` operation.
 */
export function handleGetNode(response?: HandleGetNodeResponse | HttpResponseResolver<{
    gid: string;
}, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<{
        gid: string;
    }, never>(`${options?.baseUrl ?? '*'}/nodes/:gid`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleGetNodeSubgraphResponse = {
    body: GetNodeSubgraphResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /nodes/{gid}/subgraph` operation.
 */
export function handleGetNodeSubgraph(response?: HandleGetNodeSubgraphResponse | HttpResponseResolver<{
    gid: string;
}, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<{
        gid: string;
    }, never>(`${options?.baseUrl ?? '*'}/nodes/:gid/subgraph`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleGetTopNodesResponse = {
    body: GetTopNodesResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /top` operation.
 */
export function handleGetTopNodes(response?: HandleGetTopNodesResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<never, never>(`${options?.baseUrl ?? '*'}/top`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleListClustersResponse = {
    body: ListClustersResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /clusters` operation.
 */
export function handleListClusters(response?: HandleListClustersResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<never, never>(`${options?.baseUrl ?? '*'}/clusters`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleGetClusterResponse = {
    body: GetClusterResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /clusters/{cluster_id}` operation.
 */
export function handleGetCluster(response?: HandleGetClusterResponse | HttpResponseResolver<{
    cluster_id: string;
}, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<{
        cluster_id: string;
    }, never>(`${options?.baseUrl ?? '*'}/clusters/:cluster_id`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type MswHandlerFactories = {
    /**
     * Handler for the `GET /health` operation.
     */
    getHealth: typeof handleGetHealth;
    /**
     * Handler for the `GET /meta` operation.
     */
    getMeta: typeof handleGetMeta;
    /**
     * Handler for the `POST /reload` operation.
     */
    reloadData: typeof handleReloadData;
    /**
     * Handler for the `GET /graph` operation.
     */
    getGraph: typeof handleGetGraph;
    /**
     * Handler for the `GET /search` operation.
     */
    searchNodes: typeof handleSearchNodes;
    /**
     * Handler for the `GET /nodes/{gid}` operation.
     */
    getNode: typeof handleGetNode;
    /**
     * Handler for the `GET /nodes/{gid}/subgraph` operation.
     */
    getNodeSubgraph: typeof handleGetNodeSubgraph;
    /**
     * Handler for the `GET /top` operation.
     */
    getTopNodes: typeof handleGetTopNodes;
    /**
     * Handler for the `GET /clusters` operation.
     */
    listClusters: typeof handleListClusters;
    /**
     * Handler for the `GET /clusters/{cluster_id}` operation.
     */
    getCluster: typeof handleGetCluster;
};

export type CreateMswHandlersResult = {
    all: (options?: {
        pick?: {
            [K in keyof MswHandlerFactories]?: Parameters<MswHandlerFactories[K]>[0] | Parameters<MswHandlerFactories[K]>;
        };
    }) => ReadonlyArray<HttpHandler>;
    pick: MswHandlerFactories;
};

export function createMswHandlers(config: RequestHandlerOptions = {}): CreateMswHandlersResult {
    type Handler<R> = (response?: R, options?: RequestHandlerOptions) => HttpHandler;
    function wrap<R>(handler: Handler<R>): Handler<R> {
        return (response, options) => handler(response, { ...config, ...options });
    }
    const pick: CreateMswHandlersResult['pick'] = {
        getHealth: wrap(handleGetHealth),
        getMeta: wrap(handleGetMeta),
        reloadData: wrap(handleReloadData),
        getGraph: wrap(handleGetGraph),
        searchNodes: wrap(handleSearchNodes),
        getNode: wrap(handleGetNode),
        getNodeSubgraph: wrap(handleGetNodeSubgraph),
        getTopNodes: wrap(handleGetTopNodes),
        listClusters: wrap(handleListClusters),
        getCluster: wrap(handleGetCluster)
    };
    const all: CreateMswHandlersResult['all'] = (options = {}) => {
        type OverrideValue<R> = R | [
            response?: R,
            options?: RequestHandlerOptions
        ];
        function invoke<R>(fn: Handler<R>, override?: OverrideValue<R>): HttpHandler {
            return Array.isArray(override) ? fn(...override) : fn(override);
        }
        const overrides = options.pick ?? {};
        return [
            invoke(pick.getNodeSubgraph, overrides.getNodeSubgraph),
            invoke(pick.getNode, overrides.getNode),
            invoke(pick.getCluster, overrides.getCluster),
            invoke(pick.getHealth, overrides.getHealth),
            invoke(pick.getMeta, overrides.getMeta),
            invoke(pick.reloadData, overrides.reloadData),
            invoke(pick.getGraph, overrides.getGraph),
            invoke(pick.searchNodes, overrides.searchNodes),
            invoke(pick.getTopNodes, overrides.getTopNodes),
            invoke(pick.listClusters, overrides.listClusters)
        ];
    };
    return { all, pick };
}
