// This file is auto-generated by @hey-api/openapi-ts

import { http, type HttpHandler, HttpResponse, type HttpResponseResolver, type RequestHandlerOptions as RequestHandlerOptions2 } from 'msw';

import type { ClientOptions, CreateOrderData, CreateOrderResponses, GetServiceResponses, ListServicesResponses, LoginData, LoginResponses } from './types.gen';

export type RequestHandlerOptions = RequestHandlerOptions2 & {
    baseUrl?: ClientOptions['baseUrl'];
    responseFallback?: 'error' | 'passthrough';
};

export type HandleLoginResponse = {
    body: LoginResponses[200];
    status?: 200;
};

/**
 * Handler for the `POST /auth/token` operation.
 */
export function handleLogin(response?: HandleLoginResponse | HttpResponseResolver<never, LoginData['body']>, options?: RequestHandlerOptions): HttpHandler {
    return http.post<never, LoginData['body']>(`${options?.baseUrl ?? '*'}/auth/token`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleListServicesResponse = {
    body: ListServicesResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /services` operation.
 */
export function handleListServices(response?: HandleListServicesResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<never, never>(`${options?.baseUrl ?? '*'}/services`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleGetServiceResponse = {
    body: GetServiceResponses[200];
    status?: 200;
};

/**
 * Handler for the `GET /services/{service_id}` operation.
 */
export function handleGetService(response?: HandleGetServiceResponse | HttpResponseResolver<{
    service_id: string;
}, never>, options?: RequestHandlerOptions): HttpHandler {
    return http.get<{
        service_id: string;
    }, never>(`${options?.baseUrl ?? '*'}/services/:service_id`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 200 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type HandleCreateOrderResponse = {
    body: CreateOrderResponses[201];
    status?: 201;
};

/**
 * Handler for the `POST /orders` operation.
 */
export function handleCreateOrder(response?: HandleCreateOrderResponse | HttpResponseResolver<never, CreateOrderData['body']>, options?: RequestHandlerOptions): HttpHandler {
    return http.post<never, CreateOrderData['body']>(`${options?.baseUrl ?? '*'}/orders`, info => {
        if (typeof response === 'function') {
            return response(info);
        }
        const body = response?.body;
        if (body !== undefined) {
            return HttpResponse.json(body, { status: response?.status ?? 201 });
        }
        if (options?.responseFallback === 'passthrough') {
            return;
        }
        return new Response('Not Implemented', {
            status: 501,
            statusText: 'Not Implemented'
        });
    }, options);
}

export type MswHandlerFactories = {
    /**
     * Handler for the `POST /auth/token` operation.
     */
    login: typeof handleLogin;
    /**
     * Handler for the `GET /services` operation.
     */
    listServices: typeof handleListServices;
    /**
     * Handler for the `GET /services/{service_id}` operation.
     */
    getService: typeof handleGetService;
    /**
     * Handler for the `POST /orders` operation.
     */
    createOrder: typeof handleCreateOrder;
};

export type CreateMswHandlersResult = {
    all: (options?: {
        pick?: {
            [K in keyof MswHandlerFactories]?: Parameters<MswHandlerFactories[K]>[0] | Parameters<MswHandlerFactories[K]>;
        };
    }) => ReadonlyArray<HttpHandler>;
    pick: MswHandlerFactories;
};

export function createMswHandlers(config: RequestHandlerOptions = {}): CreateMswHandlersResult {
    type Handler<R> = (response?: R, options?: RequestHandlerOptions) => HttpHandler;
    function wrap<R>(handler: Handler<R>): Handler<R> {
        return (response, options) => handler(response, { ...config, ...options });
    }
    const pick: CreateMswHandlersResult['pick'] = {
        login: wrap(handleLogin),
        listServices: wrap(handleListServices),
        getService: wrap(handleGetService),
        createOrder: wrap(handleCreateOrder)
    };
    const all: CreateMswHandlersResult['all'] = (options = {}) => {
        type OverrideValue<R> = R | [
            response?: R,
            options?: RequestHandlerOptions
        ];
        function invoke<R>(fn: Handler<R>, override?: OverrideValue<R>): HttpHandler {
            return Array.isArray(override) ? fn(...override) : fn(override);
        }
        const overrides = options.pick ?? {};
        return [
            invoke(pick.login, overrides.login),
            invoke(pick.getService, overrides.getService),
            invoke(pick.listServices, overrides.listServices),
            invoke(pick.createOrder, overrides.createOrder)
        ];
    };
    return { all, pick };
}
