// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetClusterData, GetClusterErrors, GetClusterResponses, GetGraphData, GetGraphErrors, GetGraphResponses, GetHealthData, GetHealthResponses, GetMetaData, GetMetaResponses, GetNodeData, GetNodeErrors, GetNodeResponses, GetNodeSubgraphData, GetNodeSubgraphErrors, GetNodeSubgraphResponses, GetTopNodesData, GetTopNodesErrors, GetTopNodesResponses, ListClustersData, ListClustersResponses, ReloadDataData, ReloadDataResponses, SearchNodesData, SearchNodesErrors, SearchNodesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Get Meta
 *
 * Сводка по выгрузке, источник ролей и словарь ролей для легенды.
 */
export const getMeta = <ThrowOnError extends boolean = false>(options?: Options<GetMetaData, ThrowOnError>): RequestResult<GetMetaResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMetaResponses, unknown, ThrowOnError>({ url: '/meta', ...options });

/**
 * Reload Data
 *
 * Перечитать outputs/ после прогона пайплайна, без перезапуска сервера.
 */
export const reloadData = <ThrowOnError extends boolean = false>(options?: Options<ReloadDataData, ThrowOnError>): RequestResult<ReloadDataResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ReloadDataResponses, unknown, ThrowOnError>({ url: '/reload', ...options });

/**
 * Get Graph
 *
 * Весь граф или его срез. Рёбра — только между возвращёнными узлами.
 */
export const getGraph = <ThrowOnError extends boolean = false>(options?: Options<GetGraphData, ThrowOnError>): RequestResult<GetGraphResponses, GetGraphErrors, ThrowOnError> => (options?.client ?? client).get<GetGraphResponses, GetGraphErrors, ThrowOnError>({ url: '/graph', ...options });

/**
 * Search Nodes
 *
 * Поиск по началу gid; точное совпадение идёт первым.
 */
export const searchNodes = <ThrowOnError extends boolean = false>(options: Options<SearchNodesData, ThrowOnError>): RequestResult<SearchNodesResponses, SearchNodesErrors, ThrowOnError> => (options.client ?? client).get<SearchNodesResponses, SearchNodesErrors, ThrowOnError>({ url: '/search', ...options });

/**
 * Get Node
 *
 * Карточка узла: роль с основанием, входящие и исходящие рёбра, отдельные переводы.
 */
export const getNode = <ThrowOnError extends boolean = false>(options: Options<GetNodeData, ThrowOnError>): RequestResult<GetNodeResponses, GetNodeErrors, ThrowOnError> => (options.client ?? client).get<GetNodeResponses, GetNodeErrors, ThrowOnError>({ url: '/nodes/{gid}', ...options });

/**
 * Get Node Subgraph
 *
 * Окрестность узла для экрана: узлы в radius шагов (без учёта направления), рёбра — исходные направленные.
 */
export const getNodeSubgraph = <ThrowOnError extends boolean = false>(options: Options<GetNodeSubgraphData, ThrowOnError>): RequestResult<GetNodeSubgraphResponses, GetNodeSubgraphErrors, ThrowOnError> => (options.client ?? client).get<GetNodeSubgraphResponses, GetNodeSubgraphErrors, ThrowOnError>({ url: '/nodes/{gid}/subgraph', ...options });

/**
 * Get Top Nodes
 *
 * Ранжированный список приоритетов (top_nodes.csv).
 */
export const getTopNodes = <ThrowOnError extends boolean = false>(options?: Options<GetTopNodesData, ThrowOnError>): RequestResult<GetTopNodesResponses, GetTopNodesErrors, ThrowOnError> => (options?.client ?? client).get<GetTopNodesResponses, GetTopNodesErrors, ThrowOnError>({ url: '/top', ...options });

/**
 * List Clusters
 */
export const listClusters = <ThrowOnError extends boolean = false>(options?: Options<ListClustersData, ThrowOnError>): RequestResult<ListClustersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListClustersResponses, unknown, ThrowOnError>({ url: '/clusters', ...options });

/**
 * Get Cluster
 *
 * Паспорт кластера и его подграф.
 */
export const getCluster = <ThrowOnError extends boolean = false>(options: Options<GetClusterData, ThrowOnError>): RequestResult<GetClusterResponses, GetClusterErrors, ThrowOnError> => (options.client ?? client).get<GetClusterResponses, GetClusterErrors, ThrowOnError>({ url: '/clusters/{cluster_id}', ...options });
