// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_login
 */
export type BodyLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Order
 */
export type Order = {
    /**
     * Id
     */
    id: number;
    /**
     * Service Id
     */
    service_id: number;
    /**
     * Address
     */
    address: string;
    /**
     * Status
     */
    status: string;
};

/**
 * OrderCreate
 */
export type OrderCreate = {
    /**
     * Service Id
     */
    service_id: number;
    /**
     * Address
     */
    address: string;
};

/**
 * Service
 */
export type Service = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Price
     */
    price: number;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/auth/token';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type ListServicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/services';
};

export type ListServicesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListServicesError = ListServicesErrors[keyof ListServicesErrors];

export type ListServicesResponses = {
    /**
     * Response List Services
     *
     * Successful Response
     */
    200: Array<Service>;
};

export type ListServicesResponse = ListServicesResponses[keyof ListServicesResponses];

export type GetServiceData = {
    body?: never;
    path: {
        /**
         * Service Id
         */
        service_id: number;
    };
    query?: never;
    url: '/services/{service_id}';
};

export type GetServiceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetServiceError = GetServiceErrors[keyof GetServiceErrors];

export type GetServiceResponses = {
    /**
     * Successful Response
     */
    200: Service;
};

export type GetServiceResponse = GetServiceResponses[keyof GetServiceResponses];

export type CreateOrderData = {
    body: OrderCreate;
    path?: never;
    query?: never;
    url: '/orders';
};

export type CreateOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrderError = CreateOrderErrors[keyof CreateOrderErrors];

export type CreateOrderResponses = {
    /**
     * Successful Response
     */
    201: Order;
};

export type CreateOrderResponse = CreateOrderResponses[keyof CreateOrderResponses];
