// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Body_login
 */
export const zBodyLogin = z.object({
    grant_type: z.string().regex(/^password$/).nullish(),
    username: z.string(),
    password: z.string(),
    scope: z.string().optional().default(''),
    client_id: z.string().nullish(),
    client_secret: z.string().nullish()
});

/**
 * Order
 */
export const zOrder = z.object({
    id: z.int(),
    service_id: z.int(),
    address: z.string(),
    status: z.string()
});

/**
 * OrderCreate
 */
export const zOrderCreate = z.object({
    service_id: z.int(),
    address: z.string()
});

/**
 * Service
 */
export const zService = z.object({
    id: z.int(),
    title: z.string(),
    price: z.number(),
    description: z.string().nullish()
});

/**
 * Token
 */
export const zToken = z.object({
    access_token: z.string(),
    token_type: z.string().optional().default('bearer')
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zLoginBody = zBodyLogin;

/**
 * Successful Response
 */
export const zLoginResponse = zToken;

export const zListServicesQuery = z.object({
    q: z.string().nullish(),
    limit: z.int().optional().default(20)
});

/**
 * Response List Services
 *
 * Successful Response
 */
export const zListServicesResponse = z.array(zService);

export const zGetServicePath = z.object({
    service_id: z.int()
});

/**
 * Successful Response
 */
export const zGetServiceResponse = zService;

export const zCreateOrderBody = zOrderCreate;

/**
 * Successful Response
 */
export const zCreateOrderResponse = zOrder;
