// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getCluster, getGraph, getHealth, getMeta, getNode, getNodeSubgraph, getTopNodes, listClusters, type Options, reloadData, searchNodes } from '../sdk.gen';
import type { GetClusterData, GetClusterError, GetClusterResponse, GetGraphData, GetGraphError, GetGraphResponse, GetHealthData, GetHealthResponse, GetMetaData, GetMetaResponse, GetNodeData, GetNodeError, GetNodeResponse, GetNodeSubgraphData, GetNodeSubgraphError, GetNodeSubgraphResponse, GetTopNodesData, GetTopNodesError, GetTopNodesResponse, ListClustersData, ListClustersResponse, ReloadDataData, ReloadDataResponse, SearchNodesData, SearchNodesError, SearchNodesResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

/**
 * Get Health
 */
export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, DefaultError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getMetaQueryKey = (options?: Options<GetMetaData>) => createQueryKey('getMeta', options);

/**
 * Get Meta
 *
 * Сводка по выгрузке, источник ролей и словарь ролей для легенды.
 */
export const getMetaOptions = (options?: Options<GetMetaData>) => queryOptions<GetMetaResponse, DefaultError, GetMetaResponse, ReturnType<typeof getMetaQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMeta({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMetaQueryKey(options)
});

/**
 * Reload Data
 *
 * Перечитать outputs/ после прогона пайплайна, без перезапуска сервера.
 */
export const reloadDataMutation = (options?: Partial<Options<ReloadDataData>>): UseMutationOptions<ReloadDataResponse, DefaultError, Options<ReloadDataData>> => {
    const mutationOptions: UseMutationOptions<ReloadDataResponse, DefaultError, Options<ReloadDataData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reloadData({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getGraphQueryKey = (options?: Options<GetGraphData>) => createQueryKey('getGraph', options);

/**
 * Get Graph
 *
 * Весь граф или его срез. Рёбра — только между возвращёнными узлами.
 */
export const getGraphOptions = (options?: Options<GetGraphData>) => queryOptions<GetGraphResponse, GetGraphError, GetGraphResponse, ReturnType<typeof getGraphQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGraph({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGraphQueryKey(options)
});

export const searchNodesQueryKey = (options: Options<SearchNodesData>) => createQueryKey('searchNodes', options);

/**
 * Search Nodes
 *
 * Поиск по началу gid; точное совпадение идёт первым.
 */
export const searchNodesOptions = (options: Options<SearchNodesData>) => queryOptions<SearchNodesResponse, SearchNodesError, SearchNodesResponse, ReturnType<typeof searchNodesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchNodes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchNodesQueryKey(options)
});

export const getNodeQueryKey = (options: Options<GetNodeData>) => createQueryKey('getNode', options);

/**
 * Get Node
 *
 * Карточка узла: роль с основанием, входящие и исходящие рёбра, отдельные переводы.
 */
export const getNodeOptions = (options: Options<GetNodeData>) => queryOptions<GetNodeResponse, GetNodeError, GetNodeResponse, ReturnType<typeof getNodeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNode({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNodeQueryKey(options)
});

export const getNodeSubgraphQueryKey = (options: Options<GetNodeSubgraphData>) => createQueryKey('getNodeSubgraph', options);

/**
 * Get Node Subgraph
 *
 * Окрестность узла для экрана: узлы в radius шагов (без учёта направления), рёбра — исходные направленные.
 */
export const getNodeSubgraphOptions = (options: Options<GetNodeSubgraphData>) => queryOptions<GetNodeSubgraphResponse, GetNodeSubgraphError, GetNodeSubgraphResponse, ReturnType<typeof getNodeSubgraphQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNodeSubgraph({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNodeSubgraphQueryKey(options)
});

export const getTopNodesQueryKey = (options?: Options<GetTopNodesData>) => createQueryKey('getTopNodes', options);

/**
 * Get Top Nodes
 *
 * Ранжированный список приоритетов (top_nodes.csv).
 */
export const getTopNodesOptions = (options?: Options<GetTopNodesData>) => queryOptions<GetTopNodesResponse, GetTopNodesError, GetTopNodesResponse, ReturnType<typeof getTopNodesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTopNodes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTopNodesQueryKey(options)
});

export const listClustersQueryKey = (options?: Options<ListClustersData>) => createQueryKey('listClusters', options);

/**
 * List Clusters
 */
export const listClustersOptions = (options?: Options<ListClustersData>) => queryOptions<ListClustersResponse, DefaultError, ListClustersResponse, ReturnType<typeof listClustersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listClusters({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listClustersQueryKey(options)
});

export const getClusterQueryKey = (options: Options<GetClusterData>) => createQueryKey('getCluster', options);

/**
 * Get Cluster
 *
 * Паспорт кластера и его подграф.
 */
export const getClusterOptions = (options: Options<GetClusterData>) => queryOptions<GetClusterResponse, GetClusterError, GetClusterResponse, ReturnType<typeof getClusterQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCluster({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getClusterQueryKey(options)
});
