// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createOrder, getService, listServices, login, type Options } from '../sdk.gen';
import type { CreateOrderData, CreateOrderError, CreateOrderResponse, GetServiceData, GetServiceError, GetServiceResponse, ListServicesData, ListServicesError, ListServicesResponse, LoginData, LoginError, LoginResponse } from '../types.gen';

/**
 * Login
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listServicesQueryKey = (options?: Options<ListServicesData>) => createQueryKey('listServices', options);

/**
 * List Services
 */
export const listServicesOptions = (options?: Options<ListServicesData>) => queryOptions<ListServicesResponse, ListServicesError, ListServicesResponse, ReturnType<typeof listServicesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listServices({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listServicesQueryKey(options)
});

export const getServiceQueryKey = (options: Options<GetServiceData>) => createQueryKey('getService', options);

/**
 * Get Service
 */
export const getServiceOptions = (options: Options<GetServiceData>) => queryOptions<GetServiceResponse, GetServiceError, GetServiceResponse, ReturnType<typeof getServiceQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getService({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getServiceQueryKey(options)
});

/**
 * Create Order
 */
export const createOrderMutation = (options?: Partial<Options<CreateOrderData>>): UseMutationOptions<CreateOrderResponse, CreateOrderError, Options<CreateOrderData>> => {
    const mutationOptions: UseMutationOptions<CreateOrderResponse, CreateOrderError, Options<CreateOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
